version: '2'
services:
    prototypeapp-app:
        image: prototypeapp
        external_links:
            - prototypeapp-mysql:mysql
            - prototypeapp-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/prototypeapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    prototypeapp-mysql:
        extends:
            file: mysql.yml
            service: prototypeapp-mysql
    prototypeapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: prototypeapp-elasticsearch
